#!/usr/bin/env python3
"""Test Backend — events_catalog. 12 endpoints."""
import asyncio, os, sys, tempfile
PASS = 0
FAIL = 0
def check(name, cond, detail=""):
    global PASS, FAIL
    if cond: PASS += 1; print(f"  PASS {name}")
    else: FAIL += 1; print(f"  FAIL {name} — {detail}")
async def main():
    tmp = tempfile.mkdtemp(); os.environ["AIAPP_BASE"] = tmp
    sys.path.insert(0, "/home/ubuntu/aiapp/backend"); sys.path.insert(0, "/home/ubuntu/aiapp/infra/pgsql")
    from fastapi import FastAPI; from httpx import AsyncClient, ASGITransport
    from events_catalog_api import router
    app = FastAPI(); app.include_router(router); transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as c:
        print("T01 list all")
        r = await c.get("/api/messaging/events-catalog/list")
        check("T01 total", r.json().get("total") >= 70, f"{r.json().get('total')}")
        print("T02 filter api_type")
        r2 = await c.get("/api/messaging/events-catalog/list?api_type=events")
        check("T02 count", r2.json().get("count") > 0, f"{r2.json().get('count')}")
        print("T03 filter both")
        r3 = await c.get("/api/messaging/events-catalog/list?api_type=both")
        check("T03 count", r3.json().get("count") > 0, f"{r3.json().get('count')}")
        print("T04 filter category")
        r4 = await c.get("/api/messaging/events-catalog/list?category=app")
        check("T04 count", r4.json().get("count") >= 7, f"{r4.json().get('count')}")
        print("T05 filter deprecated")
        r5 = await c.get("/api/messaging/events-catalog/list?deprecated=true")
        check("T05 count", r5.json().get("count") == 3, f"{r5.json().get('count')}")
        print("T06 search")
        r6 = await c.get("/api/messaging/events-catalog/search?q=channel")
        check("T06 found", r6.json().get("count") >= 5, f"{r6.json().get('count')}")
        print("T07 search none")
        r7 = await c.get("/api/messaging/events-catalog/search?q=zzzznonexistent")
        check("T07 none", r7.json().get("count") == 0, f"{r7.json().get('count')}")
        print("T08 categories")
        r8 = await c.get("/api/messaging/events-catalog/categories")
        check("T08 count", r8.json().get("count") == 10, f"{r8.json().get('count')}")
        print("T09 category detail")
        r9 = await c.get("/api/messaging/events-catalog/categories/channel")
        check("T09 count", r9.json().get("count") >= 10, f"{r9.json().get('count')}")
        print("T10 category 404")
        r10 = await c.get("/api/messaging/events-catalog/categories/nonexistent")
        check("T10 404", r10.status_code == 404, f"{r10.status_code}")
        print("T11 api-types")
        r11 = await c.get("/api/messaging/events-catalog/api-types")
        check("T11 count", len(r11.json().get("api_types", [])) == 3, f"{len(r11.json().get('api_types', []))}")
        print("T12 api-types/events")
        r12 = await c.get("/api/messaging/events-catalog/api-types/events")
        check("T12 count", r12.json().get("count") > 0, f"{r12.json().get('count')}")
        print("T13 api-types invalid")
        r13 = await c.get("/api/messaging/events-catalog/api-types/invalid")
        check("T13 400", r13.status_code == 400, f"{r13.status_code}")
        print("T14 subtypes")
        r14 = await c.get("/api/messaging/events-catalog/message-subtypes")
        check("T14 subtypes", r14.json().get("subtypes_count") >= 20, f"{r14.json().get('subtypes_count')}")
        check("T14 metadata", r14.json().get("metadata_events_count") == 3, f"{r14.json().get('metadata_events_count')}")
        print("T15 subscribe")
        r15 = await c.post("/api/messaging/events-catalog/subscribe", json={"event_names": ["message", "reaction_added"], "api_type": "events", "scope": "channels:history"})
        check("T15 ok", r15.json().get("ok") is True, f"{r15.json().get('ok')}")
        check("T15 created", r15.json().get("created_count") == 2, f"{r15.json().get('created_count')}")
        print("T16 subscribe dup")
        r16 = await c.post("/api/messaging/events-catalog/subscribe", json={"event_names": ["message", "pin_added"], "api_type": "events"})
        check("T16 skipped", r16.json().get("skipped_count") == 1, f"{r16.json().get('skipped_count')}")
        print("T17 subscribe invalid")
        r17 = await c.post("/api/messaging/events-catalog/subscribe", json={"event_names": ["nonexistent_event"], "api_type": "events"})
        check("T17 400", r17.status_code == 400, f"{r17.status_code}")
        print("T18 subscriptions")
        r18 = await c.get("/api/messaging/events-catalog/subscriptions")
        check("T18 count", r18.json().get("count") == 3, f"{r18.json().get('count')}")
        print("T19 scope map")
        r19 = await c.get("/api/messaging/events-catalog/scope-map")
        check("T19 count", r19.json().get("count") >= 70, f"{r19.json().get('count')}")
        check("T19 scopes", r19.json().get("unique_scopes_count") >= 10, f"{r19.json().get('unique_scopes_count')}")
        print("T20 stats")
        r20 = await c.get("/api/messaging/events-catalog/stats")
        check("T20 total", r20.json().get("total_events") >= 70, f"{r20.json().get('total_events')}")
        check("T20 cats", r20.json().get("total_categories") == 10, f"{r20.json().get('total_categories')}")
        check("T20 deprecated", r20.json().get("deprecated_count") == 3, f"{r20.json().get('deprecated_count')}")
        print("T21 event detail")
        r21 = await c.get("/api/messaging/events-catalog/app_mention")
        check("T21 name", r21.json().get("event", {}).get("name") == "app_mention", f"{r21.json().get('event', {}).get('name')}")
        print("T22 event 404")
        r22 = await c.get("/api/messaging/events-catalog/nonexistent_event_xyz")
        check("T22 404", r22.status_code == 404, f"{r22.status_code}")
    print(f"\n{'='*50}"); print(f"PASS={PASS}  FAIL={FAIL}  TOTAL={PASS+FAIL}")
    if FAIL: sys.exit(1)
if __name__ == "__main__": asyncio.run(main())
