#!/usr/bin/env python3
"""Test Backend — formatting. 7 endpoints."""
import asyncio, os, sys, tempfile
PASS = 0
FAIL = 0
def check(name, cond, detail=""):
    global PASS, FAIL
    if cond: PASS += 1; print(f"  PASS {name}")
    else: FAIL += 1; print(f"  FAIL {name} — {detail}")
async def main():
    tmp = tempfile.mkdtemp(); os.environ["AIAPP_BASE"] = tmp
    sys.path.insert(0, "/home/ubuntu/aiapp/backend"); sys.path.insert(0, "/home/ubuntu/aiapp/infra/pgsql")
    from fastapi import FastAPI; from httpx import AsyncClient, ASGITransport
    from formatting_api import router
    app = FastAPI(); app.include_router(router); transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as c:
        print("T01 format rules")
        r = await c.get("/api/messaging/formatting/format-rules")
        check("T01 count", len(r.json()) == 7, f"{len(r.json())}")
        check("T01 bold", any(x.get("description") == "Bold" for x in r.json()), "no bold")
        print("T02 preview bold")
        r2 = await c.post("/api/messaging/formatting/preview", json={"text": "*hello*"})
        check("T02 html", "<strong>hello</strong>" in r2.json().get("html", ""), f"{r2.json().get('html')}")
        print("T03 preview italic")
        r3 = await c.post("/api/messaging/formatting/preview", json={"text": "_italic_"})
        check("T03 html", "<em>italic</em>" in r3.json().get("html", ""), f"{r3.json().get('html')}")
        print("T04 preview strike")
        r4 = await c.post("/api/messaging/formatting/preview", json={"text": "~deleted~"})
        check("T04 html", "<del>deleted</del>" in r4.json().get("html", ""), f"{r4.json().get('html')}")
        print("T05 preview code")
        r5 = await c.post("/api/messaging/formatting/preview", json={"text": "`code`"})
        check("T05 html", "<code>code</code>" in r5.json().get("html", ""), f"{r5.json().get('html')}")
        print("T06 preview blockquote")
        r6 = await c.post("/api/messaging/formatting/preview", json={"text": ">quoted"})
        check("T06 html", "<blockquote>" in r6.json().get("html", ""), f"{r6.json().get('html')}")
        print("T07 preview mentions")
        r7 = await c.post("/api/messaging/formatting/preview", json={"text": "@alice @here #general"})
        html = r7.json().get("html", "")
        check("T07 user", "mention-user" in html, "no user")
        check("T07 special", "mention-special" in html, "no special")
        check("T07 channel", "mention-channel" in html, "no channel")
        print("T08 list emojis")
        r8 = await c.get("/api/messaging/formatting/emojis")
        check("T08 count", len(r8.json()) == 10, f"{len(r8.json())}")
        print("T09 create emoji")
        r9 = await c.post("/api/messaging/formatting/emojis", json={"name": "partyparrot", "value": ":partyparrot:"})
        check("T09 201", r9.status_code == 201, f"{r9.status_code}")
        check("T09 custom", r9.json().get("custom") is True, f"{r9.json().get('custom')}")
        print("T10 dup emoji")
        r10 = await c.post("/api/messaging/formatting/emojis", json={"name": "partyparrot", "value": ":partyparrot:"})
        check("T10 409", r10.status_code == 409, f"{r10.status_code}")
        print("T11 delete emoji")
        r11 = await c.delete("/api/messaging/formatting/emojis/partyparrot")
        check("T11 deleted", r11.json().get("status") == "deleted", f"{r11.json().get('status')}")
        print("T12 delete 404")
        r12 = await c.delete("/api/messaging/formatting/emojis/nonexistent")
        check("T12 404", r12.status_code == 404, f"{r12.status_code}")
        print("T13 parse mentions user")
        r13 = await c.post("/api/messaging/formatting/parse-mentions", json={"text": "Hello @alice and @bob"})
        check("T13 count", len(r13.json()) == 2, f"{len(r13.json())}")
        print("T14 parse mentions special")
        r14 = await c.post("/api/messaging/formatting/parse-mentions", json={"text": "@here @channel @everyone"})
        check("T14 count", len(r14.json()) == 3, f"{len(r14.json())}")
        print("T15 parse mentions channel")
        r15 = await c.post("/api/messaging/formatting/parse-mentions", json={"text": "#general and #random"})
        check("T15 count", len(r15.json()) == 2, f"{len(r15.json())}")
        print("T16 parse none")
        r16 = await c.post("/api/messaging/formatting/parse-mentions", json={"text": "no mentions"})
        check("T16 empty", len(r16.json()) == 0, f"{len(r16.json())}")
        print("T17 escape")
        r17 = await c.post("/api/messaging/formatting/escape", json={"text": "<script>alert(1)</script>"})
        esc = r17.json().get("escaped", "")
        check("T17 lt", "&lt;" in esc, "no lt")
        check("T17 gt", "&gt;" in esc, "no gt")
        print("T18 escape amp")
        r18 = await c.post("/api/messaging/formatting/escape", json={"text": "A & B"})
        check("T18 amp", "&amp;" in r18.json().get("escaped", ""), "no amp")
    print(f"\n{'='*50}"); print(f"PASS={PASS}  FAIL={FAIL}  TOTAL={PASS+FAIL}")
    if FAIL: sys.exit(1)
if __name__ == "__main__": asyncio.run(main())
