#!/usr/bin/env python3
"""Test Backend — ai_search. 11 endpoints."""
import asyncio, os, sys, tempfile
PASS = 0
FAIL = 0
def check(name, cond, detail=""):
    global PASS, FAIL
    if cond: PASS += 1; print(f"  PASS {name}")
    else: FAIL += 1; print(f"  FAIL {name} — {detail}")
async def main():
    tmp = tempfile.mkdtemp(); os.environ["AIAPP_BASE"] = tmp
    sys.path.insert(0, "/home/ubuntu/aiapp/backend"); sys.path.insert(0, "/home/ubuntu/aiapp/infra/pgsql")
    from fastapi import FastAPI; from httpx import AsyncClient, ASGITransport
    from ai_search_api import router
    app = FastAPI(); app.include_router(router); transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as c:
        print("T01 search")
        r = await c.get("/api/messaging/ai-search/search?q=test")
        check("T01 ok", r.status_code == 200, f"{r.status_code}")
        print("T02 search type")
        r2 = await c.get("/api/messaging/ai-search/search?q=test&type=semantic")
        check("T02 ok", r2.status_code == 200, f"{r2.status_code}")
        print("T03 natural search")
        r3 = await c.post("/api/messaging/ai-search/search/natural", json={"query": "find deployment"})
        check("T03 ok", r3.status_code == 200, f"{r3.status_code}")
        check("T03 confidence", r3.json().get("confidence") is not None, f"{list(r3.json().keys())}")
        print("T04 filters")
        r4 = await c.get("/api/messaging/ai-search/search/filters")
        check("T04 ok", r4.status_code == 200, f"{r4.status_code}")
        print("T05 list recaps")
        r5 = await c.get("/api/messaging/ai-search/recaps")
        check("T05 count", isinstance(r5.json(), list) and len(r5.json()) >= 5, f"len={len(r5.json()) if isinstance(r5.json(), list) else 'N/A'}")
        print("T06 recap detail")
        r6 = await c.get("/api/messaging/ai-search/recaps/C001")
        check("T06 ok", r6.status_code == 200, f"{r6.status_code}")
        print("T07 recap 404")
        r7 = await c.get("/api/messaging/ai-search/recaps/fake")
        check("T07 404", r7.status_code == 404, f"{r7.status_code}")
        print("T08 generate recap")
        r8 = await c.post("/api/messaging/ai-search/recaps/generate", json={"channel_id": "C001", "period": "daily"})
        check("T08 ok", r8.status_code in (200, 201), f"{r8.status_code}")
        print("T09 list summaries")
        r9 = await c.get("/api/messaging/ai-search/summaries")
        check("T09 count", isinstance(r9.json(), list) and len(r9.json()) >= 5, f"len={len(r9.json()) if isinstance(r9.json(), list) else 'N/A'}")
        print("T10 generate summary")
        r10 = await c.post("/api/messaging/ai-search/summaries/generate", json={"channel_id": "C001", "thread_ts": "1709000000.000100"})
        check("T10 ok", r10.status_code in (200, 201), f"{r10.status_code}")
        print("T11 list assistants")
        r11 = await c.get("/api/messaging/ai-search/assistants")
        check("T11 count", isinstance(r11.json(), list) and len(r11.json()) >= 4, f"len={len(r11.json()) if isinstance(r11.json(), list) else 'N/A'}")
        print("T12 assistant detail")
        r12 = await c.get("/api/messaging/ai-search/assistants/ast01")
        check("T12 ok", r12.status_code == 200, f"{r12.status_code}")
        check("T12 name", r12.json().get("name") is not None, f"{list(r12.json().keys())}")
        print("T13 assistant 404")
        r13 = await c.get("/api/messaging/ai-search/assistants/fake")
        check("T13 404", r13.status_code == 404, f"{r13.status_code}")
        print("T14 create assistant")
        r14 = await c.post("/api/messaging/ai-search/assistants", json={"name": "test-bot", "model": "gpt-4", "status": "active"})
        check("T14 ok", r14.status_code in (200, 201), f"{r14.status_code}")
        new_id = r14.json().get("id", "")
        check("T14 id", new_id != "", "no id")
        print("T15 delete assistant")
        r15 = await c.delete(f"/api/messaging/ai-search/assistants/{new_id}")
        check("T15 ok", r15.status_code == 200, f"{r15.status_code}")
        print("T16 delete 404")
        r16 = await c.delete("/api/messaging/ai-search/assistants/fake")
        check("T16 404", r16.status_code == 404, f"{r16.status_code}")
    print(f"\n{'='*50}"); print(f"PASS={PASS}  FAIL={FAIL}  TOTAL={PASS+FAIL}")
    if FAIL: sys.exit(1)
if __name__ == "__main__": asyncio.run(main())
