#!/usr/bin/env python3
"""Test Backend — incoming_webhooks. 12 endpoints."""
import asyncio, os, sys, tempfile
PASS = 0
FAIL = 0
def check(name, cond, detail=""):
    global PASS, FAIL
    if cond: PASS += 1; print(f"  PASS {name}")
    else: FAIL += 1; print(f"  FAIL {name} — {detail}")
async def main():
    tmp = tempfile.mkdtemp(); os.environ["AIAPP_BASE"] = tmp
    sys.path.insert(0, "/home/ubuntu/aiapp/backend"); sys.path.insert(0, "/home/ubuntu/aiapp/infra/pgsql")
    from fastapi import FastAPI; from httpx import AsyncClient, ASGITransport
    from incoming_webhooks_api import router
    app = FastAPI(); app.include_router(router); transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as c:
        print("T01 list webhooks")
        r = await c.get("/api/messaging/incoming-webhooks/list")
        check("T01 total", r.json().get("total") == 5, f"{r.json().get('total')}")
        print("T02 filter enabled")
        r2 = await c.get("/api/messaging/incoming-webhooks/list?enabled=true")
        check("T02 enabled", r2.json().get("count") == 4, f"{r2.json().get('count')}")
        r2b = await c.get("/api/messaging/incoming-webhooks/list?enabled=false")
        check("T02 disabled", r2b.json().get("count") == 1, f"{r2b.json().get('count')}")
        print("T03 config")
        r3 = await c.get("/api/messaging/incoming-webhooks/config")
        check("T03 enabled", r3.json().get("config", {}).get("enable_webhooks") is True, f"{r3.json().get('config')}")
        print("T04 stats")
        r4 = await c.get("/api/messaging/incoming-webhooks/stats")
        check("T04 total", r4.json().get("total_webhooks") == 5, f"{r4.json().get('total_webhooks')}")
        check("T04 success", r4.json().get("success_deliveries") == 4, f"{r4.json().get('success_deliveries')}")
        check("T04 errors", r4.json().get("error_deliveries") == 2, f"{r4.json().get('error_deliveries')}")
        print("T05 detail")
        r5 = await c.get("/api/messaging/incoming-webhooks/wh01")
        check("T05 name", r5.json().get("webhook", {}).get("name") == "ci-notifications", f"{r5.json().get('webhook')}")
        check("T05 endpoint", r5.json().get("endpoint") == "/hooks/wh01", f"{r5.json().get('endpoint')}")
        print("T06 404")
        r6 = await c.get("/api/messaging/incoming-webhooks/nonexistent")
        check("T06 404", r6.status_code == 404, f"{r6.status_code}")
        print("T07 create")
        r7 = await c.post("/api/messaging/incoming-webhooks", json={"name": "test-hook", "description": "Test", "channel": "test-ch"})
        check("T07 ok", r7.json().get("ok") is True, f"{r7.json().get('ok')}")
        new_id = r7.json().get("webhook", {}).get("id", "")
        check("T07 id", new_id != "", "no id")
        print("T08 dup name")
        r8 = await c.post("/api/messaging/incoming-webhooks", json={"name": "test-hook", "description": "dup", "channel": "ch"})
        check("T08 400", r8.status_code == 400, f"{r8.status_code}")
        print("T09 update")
        r9 = await c.put(f"/api/messaging/incoming-webhooks/{new_id}", json={"description": "Updated"})
        check("T09 ok", r9.json().get("ok") is True, f"{r9.json().get('ok')}")
        check("T09 desc", r9.json().get("webhook", {}).get("description") == "Updated", f"{r9.json().get('webhook')}")
        print("T10 send enabled")
        r10 = await c.post("/api/messaging/incoming-webhooks/wh01/send", json={"text": "Build passed!"})
        check("T10 ok", r10.json().get("ok") is True, f"{r10.json().get('ok')}")
        check("T10 bot", r10.json().get("post", {}).get("is_bot") is True, f"{r10.json().get('post')}")
        print("T11 send disabled")
        r11 = await c.post("/api/messaging/incoming-webhooks/wh04/send", json={"text": "test"})
        check("T11 403", r11.status_code == 403, f"{r11.status_code}")
        print("T12 send empty")
        r12 = await c.post("/api/messaging/incoming-webhooks/wh01/send", json={})
        check("T12 400", r12.status_code == 400, f"{r12.status_code}")
        print("T13 test enabled")
        r13 = await c.post("/api/messaging/incoming-webhooks/wh01/test")
        check("T13 ok", r13.json().get("ok") is True, f"{r13.json().get('ok')}")
        check("T13 channel", r13.json().get("channel") == "engineering", f"{r13.json().get('channel')}")
        print("T14 test disabled")
        r14 = await c.post("/api/messaging/incoming-webhooks/wh04/test")
        check("T14 not_ok", r14.json().get("ok") is False, f"{r14.json().get('ok')}")
        print("T15 deliveries")
        r15 = await c.get("/api/messaging/incoming-webhooks/wh01/deliveries")
        check("T15 id", r15.json().get("webhook_id") == "wh01", f"{r15.json().get('webhook_id')}")
        check("T15 total", r15.json().get("total") >= 4, f"{r15.json().get('total')}")
        print("T16 deliveries 404")
        r16 = await c.get("/api/messaging/incoming-webhooks/fake/deliveries")
        check("T16 404", r16.status_code == 404, f"{r16.status_code}")
        print("T17 slack-compat")
        r17 = await c.post("/api/messaging/incoming-webhooks/wh05/slack-compat", json={"text": "*bold* <https://x.com|link>"})
        check("T17 ok", r17.json().get("ok") is True, f"{r17.json().get('ok')}")
        check("T17 translated", r17.json().get("post", {}).get("slack_translated") is True, f"{r17.json().get('post')}")
        print("T18 update config")
        r18 = await c.put("/api/messaging/incoming-webhooks/config", json={"enable_debug": True})
        check("T18 ok", r18.json().get("ok") is True, f"{r18.json().get('ok')}")
        check("T18 debug", r18.json().get("config", {}).get("enable_debug") is True, f"{r18.json().get('config')}")
        print("T19 delete")
        r19 = await c.delete(f"/api/messaging/incoming-webhooks/{new_id}")
        check("T19 ok", r19.json().get("ok") is True, f"{r19.json().get('ok')}")
        print("T20 delete 404")
        r20 = await c.delete("/api/messaging/incoming-webhooks/fake")
        check("T20 404", r20.status_code == 404, f"{r20.status_code}")
    print(f"\n{'='*50}"); print(f"PASS={PASS}  FAIL={FAIL}  TOTAL={PASS+FAIL}")
    if FAIL: sys.exit(1)
if __name__ == "__main__": asyncio.run(main())
