#!/usr/bin/env python3
"""Test Backend — federation. 15 endpoints."""
import asyncio, os, sys, tempfile
PASS = 0
FAIL = 0
def check(name, cond, detail=""):
    global PASS, FAIL
    if cond: PASS += 1; print(f"  PASS {name}")
    else: FAIL += 1; print(f"  FAIL {name} — {detail}")
async def main():
    tmp = tempfile.mkdtemp(); os.environ["AIAPP_BASE"] = tmp
    sys.path.insert(0, "/home/ubuntu/aiapp/backend"); sys.path.insert(0, "/home/ubuntu/aiapp/infra/pgsql")
    from fastapi import FastAPI; from httpx import AsyncClient, ASGITransport
    from federation_api import router
    app = FastAPI(); app.include_router(router); transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as c:
        print("T01 server version")
        r = await c.get("/api/messaging/federation/version")
        check("T01 name", r.json().get("server", {}).get("name") == "aiapp-federation", f"{r.json().get('server')}")
        check("T01 rooms", len(r.json().get("supported_room_versions", [])) == 3, f"{len(r.json().get('supported_room_versions', []))}")
        print("T02 server keys")
        r2 = await c.get("/api/messaging/federation/keys")
        keys = r2.json().get("server_keys", [])
        check("T02 count", len(keys) >= 1, f"{len(keys)}")
        check("T02 ed25519", "ed25519:auto" in keys[0].get("verify_keys", {}), "no ed25519")
        print("T03 query keys")
        r3 = await c.post("/api/messaging/federation/keys/query", json={"server_keys": {"localhost": {}, "other.com": {}}})
        check("T03 queried", r3.json().get("queried_count") == 2, f"{r3.json().get('queried_count')}")
        check("T03 localhost", len(r3.json().get("server_keys", {}).get("localhost", [])) >= 1, "no localhost")
        print("T04 send PDUs")
        r4 = await c.put("/api/messaging/federation/send", json={"origin": "remote.server", "pdus": [{"type": "m.room.message", "room_id": "!room1:remote.server", "sender": "@alice:remote.server", "content": {"body": "Hello"}, "event_id": "$ev1", "state_key": None, "depth": 1, "origin_server_ts": 1709000000000}], "edus": []})
        check("T04 pdu", r4.json().get("pdu_count") == 1, f"{r4.json().get('pdu_count')}")
        check("T04 txn", r4.json().get("txn_id") != "", "no txn_id")
        print("T05 send EDUs")
        r5 = await c.put("/api/messaging/federation/send", json={"origin": "remote.server", "pdus": [{"type": "m.room.member", "room_id": "!room1:remote.server", "sender": "@bob:remote.server", "state_key": "@bob:remote.server", "content": {"membership": "join"}, "event_id": "$ev2", "depth": 2, "origin_server_ts": 1709000001000}], "edus": [{"edu_type": "m.presence", "content": {"user_id": "@alice:remote.server", "presence": "online", "last_active_ago": 5000, "currently_active": True, "status_msg": "Working"}}]})
        check("T05 edu", r5.json().get("edu_count") == 1, f"{r5.json().get('edu_count')}")
        print("T06 get event")
        r6 = await c.get("/api/messaging/federation/event/$ev1")
        check("T06 type", r6.json().get("event", {}).get("type") == "m.room.message", f"{r6.json().get('event')}")
        print("T07 event 404")
        r7 = await c.get("/api/messaging/federation/event/$nonexistent")
        check("T07 404", r7.status_code == 404, f"{r7.status_code}")
        print("T08 room state")
        r8 = await c.get("/api/messaging/federation/state/!room1:remote.server")
        check("T08 state", r8.json().get("state_count") >= 1, f"{r8.json().get('state_count')}")
        print("T09 state IDs")
        r9 = await c.get("/api/messaging/federation/state-ids/!room1:remote.server")
        check("T09 ids", len(r9.json().get("pdu_ids", [])) >= 1, f"{len(r9.json().get('pdu_ids', []))}")
        print("T10 backfill")
        r10 = await c.get("/api/messaging/federation/backfill/!room1:remote.server?limit=10")
        check("T10 count", r10.json().get("count") >= 2, f"{r10.json().get('count')}")
        print("T11 missing events")
        r11 = await c.post("/api/messaging/federation/missing-events/!room1:remote.server", json={"earliest_events": ["$ev1"], "latest_events": ["$ev2"], "limit": 10})
        check("T11 room", r11.json().get("room_id") == "!room1:remote.server", f"{r11.json().get('room_id')}")
        print("T12 make-join")
        r12 = await c.get("/api/messaging/federation/make-join/!room1:remote.server/@charlie:local")
        check("T12 version", r12.json().get("room_version") == "3", f"{r12.json().get('room_version')}")
        check("T12 sender", r12.json().get("event", {}).get("sender") == "@charlie:local", f"{r12.json().get('event')}")
        print("T13 send-join")
        r13 = await c.put("/api/messaging/federation/send-join/!room1:remote.server/$ev_join", json={"event": {"type": "m.room.member", "sender": "@charlie:local", "state_key": "@charlie:local", "content": {"membership": "join"}, "depth": 3, "origin_server_ts": 1709000002000}})
        check("T13 room", r13.json().get("room_id") == "!room1:remote.server", f"{r13.json().get('room_id')}")
        check("T13 state", len(r13.json().get("state", [])) >= 1, f"{len(r13.json().get('state', []))}")
        print("T14 send-leave")
        r14 = await c.put("/api/messaging/federation/send-leave/!room1:remote.server/$ev_leave", json={"event": {"type": "m.room.member", "sender": "@charlie:local", "state_key": "@charlie:local", "content": {}, "depth": 4, "origin_server_ts": 1709000003000}})
        check("T14 status", r14.json().get("status") == "left", f"{r14.json().get('status')}")
        print("T15 public rooms")
        r15 = await c.get("/api/messaging/federation/public-rooms?limit=20")
        check("T15 chunk", isinstance(r15.json().get("chunk"), list), "not list")
        print("T16 hierarchy")
        r16 = await c.get("/api/messaging/federation/hierarchy/!room1:remote.server")
        check("T16 room", r16.json().get("room") is not None, "no room")
        print("T17 presence")
        r17 = await c.get("/api/messaging/federation/presence?user_ids=@alice:remote.server")
        check("T17 count", r17.json().get("count") == 1, f"{r17.json().get('count')}")
        check("T17 online", r17.json().get("presence", [{}])[0].get("presence") == "online", f"{r17.json().get('presence')}")
        print("T18 presence empty")
        r18 = await c.get("/api/messaging/federation/presence?user_ids=@unknown:x")
        check("T18 empty", r18.json().get("count") == 0, f"{r18.json().get('count')}")
    print(f"\n{'='*50}"); print(f"PASS={PASS}  FAIL={FAIL}  TOTAL={PASS+FAIL}")
    if FAIL: sys.exit(1)
if __name__ == "__main__": asyncio.run(main())
