#!/usr/bin/env python3
"""Test Backend — events_api. 12 endpoints."""
import asyncio, os, sys, tempfile
PASS = 0
FAIL = 0
def check(name, cond, detail=""):
    global PASS, FAIL
    if cond: PASS += 1; print(f"  PASS {name}")
    else: FAIL += 1; print(f"  FAIL {name} — {detail}")
async def main():
    tmp = tempfile.mkdtemp(); os.environ["AIAPP_BASE"] = tmp
    sys.path.insert(0, "/home/ubuntu/aiapp/backend"); sys.path.insert(0, "/home/ubuntu/aiapp/infra/pgsql")
    from fastapi import FastAPI; from httpx import AsyncClient, ASGITransport
    from events_api_api import router
    app = FastAPI(); app.include_router(router); transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as c:
        print("T01 list subscriptions empty")
        r = await c.get("/api/messaging/events-api/subscriptions")
        check("T01 count", r.json().get("count") == 0, f"{r.json().get('count')}")
        check("T01 enabled", r.json().get("enabled_count") == 0, f"{r.json().get('enabled_count')}")
        print("T02 create subscription")
        r2 = await c.post("/api/messaging/events-api/subscriptions", json={"event_type": "message", "scope": "channels:history", "mode": "events_api", "request_url": "https://example.com/hook"})
        sub_id = r2.json().get("id", "")
        check("T02 id", sub_id != "", "no id")
        check("T02 type", r2.json().get("event_type") == "message", f"{r2.json().get('event_type')}")
        check("T02 enabled", r2.json().get("enabled") is True, f"{r2.json().get('enabled')}")
        print("T03 create second")
        r3 = await c.post("/api/messaging/events-api/subscriptions", json={"event_type": "reaction_added", "scope": "reactions:read", "mode": "events_api", "request_url": "https://example.com/hook2"})
        sub2_id = r3.json().get("id", "")
        check("T03 id", sub2_id != "", "no id")
        print("T04 list subscriptions")
        r4 = await c.get("/api/messaging/events-api/subscriptions")
        check("T04 count", r4.json().get("count") == 2, f"{r4.json().get('count')}")
        check("T04 enabled", r4.json().get("enabled_count") == 2, f"{r4.json().get('enabled_count')}")
        print("T05 update disable")
        r5 = await c.put(f"/api/messaging/events-api/subscriptions/{sub2_id}", json={"enabled": False})
        check("T05 disabled", r5.json().get("enabled") is False, f"{r5.json().get('enabled')}")
        print("T06 list after disable")
        r6 = await c.get("/api/messaging/events-api/subscriptions")
        check("T06 enabled", r6.json().get("enabled_count") == 1, f"{r6.json().get('enabled_count')}")
        print("T07 delete")
        r7 = await c.delete(f"/api/messaging/events-api/subscriptions/{sub2_id}")
        check("T07 deleted", r7.json().get("status") == "deleted", f"{r7.json().get('status')}")
        print("T08 delete 404")
        r8 = await c.delete("/api/messaging/events-api/subscriptions/nonexistent")
        check("T08 404", r8.status_code == 404, f"{r8.status_code}")
        print("T09 receive event")
        r9 = await c.post("/api/messaging/events-api/webhook", json={"type": "event_callback", "app_id": "A001", "team_id": "T001", "enterprise_id": "", "event": {"type": "message", "text": "Hello"}, "event_time": 1709000000, "authorizations": [{"enterprise_id": "", "team_id": "T001", "user_id": "U001", "is_bot": False, "is_enterprise_install": False}]})
        check("T09 ok", r9.json().get("ok") is True, f"{r9.json().get('ok')}")
        ev_id = r9.json().get("event_id", "")
        check("T09 id", ev_id != "", "no event_id")
        check("T09 matched", r9.json().get("subscriptions_matched") == 1, f"{r9.json().get('subscriptions_matched')}")
        print("T10 unmatched event")
        r10 = await c.post("/api/messaging/events-api/webhook", json={"type": "event_callback", "app_id": "A001", "team_id": "T001", "enterprise_id": "", "event": {"type": "file_shared"}, "event_time": 1709000001, "authorizations": []})
        check("T10 ok", r10.json().get("ok") is True, f"{r10.json().get('ok')}")
        check("T10 matched", r10.json().get("subscriptions_matched") == 0, f"{r10.json().get('subscriptions_matched')}")
        print("T11 list events")
        r11 = await c.get("/api/messaging/events-api/events")
        check("T11 count", r11.json().get("count") == 2, f"{r11.json().get('count')}")
        print("T12 filter events")
        r12 = await c.get("/api/messaging/events-api/events?event_type=message")
        check("T12 count", r12.json().get("count") == 1, f"{r12.json().get('count')}")
        print("T13 event detail")
        r13 = await c.get(f"/api/messaging/events-api/events/{ev_id}")
        check("T13 type", r13.json().get("event", {}).get("event_type") == "message", f"{r13.json().get('event', {}).get('event_type')}")
        check("T13 auths", r13.json().get("authorizations_count") == 1, f"{r13.json().get('authorizations_count')}")
        print("T14 event 404")
        r14 = await c.get("/api/messaging/events-api/events/nonexistent")
        check("T14 404", r14.status_code == 404, f"{r14.status_code}")
        print("T15 authorizations")
        r15 = await c.post("/api/messaging/events-api/authorizations", json={"event_id": ev_id})
        check("T15 count", r15.json().get("count") == 1, f"{r15.json().get('count')}")
        check("T15 no_bot", r15.json().get("has_bot") is False, f"{r15.json().get('has_bot')}")
        print("T16 authorizations 404")
        r16 = await c.post("/api/messaging/events-api/authorizations", json={"event_id": "fake"})
        check("T16 404", r16.status_code == 404, f"{r16.status_code}")
        print("T17 rate limits")
        r17 = await c.get("/api/messaging/events-api/rate-limits")
        check("T17 count", r17.json().get("events_count") == 2, f"{r17.json().get('events_count')}")
        check("T17 limit", r17.json().get("limit") == 30000, f"{r17.json().get('limit')}")
        check("T17 not_limited", r17.json().get("is_limited") is False, f"{r17.json().get('is_limited')}")
        print("T18 retry config")
        r18 = await c.post("/api/messaging/events-api/retry-config", json={"retries_enabled": True, "delayed_retry_enabled": True, "max_retries": 5})
        check("T18 max", r18.json().get("max_retries") == 5, f"{r18.json().get('max_retries')}")
        check("T18 schedule", len(r18.json().get("retry_schedule", [])) >= 5, f"{len(r18.json().get('retry_schedule', []))}")
        print("T19 config")
        r19 = await c.get("/api/messaging/events-api/config")
        check("T19 max", r19.json().get("config", {}).get("max_retries") == 5, f"{r19.json().get('config', {}).get('max_retries')}")
        check("T19 reasons", len(r19.json().get("retry_reasons", [])) == 6, f"{len(r19.json().get('retry_reasons', []))}")
        check("T19 lifecycle", len(r19.json().get("lifecycle_events", [])) == 3, f"{len(r19.json().get('lifecycle_events', []))}")
        print("T20 verify-url valid")
        r20 = await c.post("/api/messaging/events-api/verify-url", json={"type": "url_verification", "challenge": "test_123", "token": "tok"})
        check("T20 challenge", r20.json().get("challenge") == "test_123", f"{r20.json().get('challenge')}")
        print("T21 verify-url bad")
        r21 = await c.post("/api/messaging/events-api/verify-url", json={"type": "event_callback", "challenge": "x", "token": "t"})
        check("T21 400", r21.status_code == 400, f"{r21.status_code}")
    print(f"\n{'='*50}"); print(f"PASS={PASS}  FAIL={FAIL}  TOTAL={PASS+FAIL}")
    if FAIL: sys.exit(1)
if __name__ == "__main__": asyncio.run(main())
